Repository knative-sandbox/eventing-awssqs, pull requests merged in 2020-11, with the labels that each got.

#17 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/L

#18 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/S

#19 update deps to latest 0.19
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/kncloudevents/http_client.go
  vendor/knative.dev/eventing/pkg/kncloudevents/message_sender.go
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/performance-tests.sh
  vendor/knative.dev/pkg/version/version.go
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/performance-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#20 Fix a few more occurrences of divisive language
  config/placeholder.go
Labels: approved, cla: yes, lgtm, size/XS

#21 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#22 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS
