Repository knative-sandbox/eventing-awssqs, pull requests merged in 2021-04, with the labels that each got.

#73 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/injection/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#75 Move all scripts to use hack rather than test-infra
  go.mod
  go.sum
  hack/release.sh
  hack/tools.go
  hack/update-deps.sh
  hack/verify-codegen.sh
  test/presubmit-tests.sh
  vendor/knative.dev/test-infra/LICENSE
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/codegen-library.sh
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/infra-library.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/microbenchmarks.sh
  vendor/knative.dev/test-infra/scripts/performance-tests.sh
  vendor/knative.dev/test-infra/scripts/placeholder.go
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/knative.dev/test-infra/scripts/release.sh
  vendor/knative.dev/test-infra/scripts/shellcheck-presubmit.sh
  vendor/knative.dev/test-infra/scripts/update-test-infra.sh
  vendor/modules.txt
Labels: cla: yes, lgtm, size/XXL

#76 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/injection/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S
