Repository knative-sandbox/eventing-awssqs, pull requests merged in 2021-08, with the labels that each got.

#111 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#110 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, lgtm, approved, size/S

#112 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/S

#118 Use `controller.Impl` tracker and cleanups
  pkg/reconciler/controller.go
Labels: cla: yes, size/XS, lgtm, approved

#117 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/broker_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/in_memory_channel_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/in_memory_channel_types.go
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/knative.dev/pkg/test/helpers/name.go
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: cla: yes, size/M, lgtm, approved

#116 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: cla: yes, size/XS, lgtm, approved

#113 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, lgtm, approved, size/S

#123 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, lgtm, approved, size/S
